version: "3.7"

services:
  web:
    build: ./app
    container_name: heroku-web
    command: python main.py run -h 0.0.0.0
    env_file:
      - config/.env.dev
    restart: always
    ports:
    - 5000:5000