version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./flask.Dockerfile
    container_name: flask
    command: python main.py run -h 0.0.0.0
    volumes:
    - ./app/:/usr/src/app
    restart: always
    ports:
    - 8080:8080